version: '3.5'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
        - "22181:2181"
    networks:
      - degressly_network

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper

    container_name: kafka
    networks:
      - degressly_network
    ports:
      - "9092:29092"
    environment:
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  degressly-comparator:
    image: degressly-comparator
    container_name: degressly-comparator
    networks:
      - degressly_network
    env_file:
      - .env

    depends_on:
      - kafka

networks:
  degressly_network:
    name: degressly_example_network